title: Games by Nathan Scott
description: An indie game dev blog and portfolio by Nathan Scott.

remote_theme: tajacks/lightspeed

url: "https://ncscott.dev"
baseurl: ""

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate-v2