title: My Lightspeed Site
description: A fast, simple Jekyll site

remote_theme: tajacks/lightspeed

baseurl: "/ncscott.dev"
url: ""

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2